resolver: lts-10.8
packages:
- .
extra-deps:
- git: https://github.com/ucsd-progsys/liquidhaskell.git
  commit: 3e1bbfa1b58eba434222893d1ee75fcfeecfb7a6
- git: https://github.com/ucsd-progsys/liquid-fixpoint.git
  commit: fb1f8bb3e6dca9b3c474d2f1c15a49aee241e897
- dotgen-0.4.2
- fgl-visualize-0.1.0.1
- located-base-0.1.1.1