version: 2
jobs:
  test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            rsync -ave --exclude='.circleci' ./ .circleci/code
            docker-compose -f .circleci/docker-compose.yml build --build-arg resolver=$(cat stack.yaml | sed -n '/resolver:/p' | sed -r 's/resolver:\s(.*)/\1/') app
      - restore_cache:
          keys:
            - stack-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - stack-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "stack.yaml" }}-
            - stack-{{ .Environment.COMMON_CACHE_KEY }}-
      - run:
          name: Run stack test
          command:
            docker-compose -f .circleci/docker-compose.yml run app stack test --fast --allow-different-user
      - save_cache:
          key: stack-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - .circleci/code/.stack-work
  hlint:
    docker:
      - image: ubuntu:16.04
    steps:
      - checkout
      - run:
          name: Run HLint
          command: |
            apt update
            apt install -y curl
            curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s -- --version
            curl -sL https://raw.github.com/ndmitchell/hlint/master/misc/travis.sh | sh -s .
  pedantic:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build docker image
          command: |
            rsync -ave --exclude='.circleci' ./ .circleci/code
            docker-compose -f .circleci/docker-compose.yml build --build-arg resolver=$(cat stack.yaml | sed -n '/resolver:/p' | sed -r 's/resolver:\s(.*)/\1/') app
      - restore_cache:
          keys:
            - stack-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - stack-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "stack.yaml" }}-
            - stack-{{ .Environment.COMMON_CACHE_KEY }}-
      - run:
          name: Run stack test --pedantic
          command: |
            docker-compose -f .circleci/docker-compose.yml run app stack clean --allow-different-user
            docker-compose -f .circleci/docker-compose.yml run app stack test --pedantic --fast --allow-different-user
      - save_cache:
          key: stack-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - .circleci/code/.stack-work
  liquidhaskell:
    docker:
      - image: waddlaw/liquidhaskell:0.8.0.5
    steps:
      - checkout
      - run:
          name: Run LiquidHaskell
          command: |
            ls
            liquid
workflows:
  version: 2
  test-hlint-pedantic:
    jobs:
      - test
      - hlint:
          requires:
            - test
      - pedantic:
          requires:
            - test
      - liquidhaskell:
          requires:
            - test